server:
  port: 8082

spring:
  application:
    name: university-service
  datasource:
    url: jdbc:postgresql://localhost:5432/university_db
    username: postgres
    password: andaset2005
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/